name: OWASP Dependency Checker

on:
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          scan-only: true
          report-file: dependency-check-report.xml
